CREATE TABLE PUBLIC.Usuarios(
	id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
	nombre text,
	apellido text,
	edad int
)

INSERT INTO PUBLIC.Usuarios( nombre, apellido, edad) 
VALUES	('euclides','perez',27 ),
		('ana', 'velez', 23)

/*Select All*/
select * from public.Usuarios

/*Select Always*/
SELECT id, nombre FROM Usuarios

/*Select for id*/
Select * from Usuarios where id = 1