create table if exists public.turnos_medicos(
	id int primary key generated by default as identity (increment 1 start 1 ),
	profesional text,
	id_usuario int,
	motivo text,
	horaio text,
	constraint FK_usuario foreign key  (id_usuario) references public.Usuarios(id)
)
/*relacion 1 a muchos la clave de un pasa a ser clave foranea de muchos
 en un usuario puede tener muchos turnos pero un turno no puede tener a mas de un 
 usuario*/

insert into public.turnos_medicos(profesional, id_usuario, motivo, horaio)
	values	('Albert  Einsten', 2, 'Pensamiento', '12:30:pm'),
			('Nicola Tesla', 2, 'Memorizar', '01:30:pm')
			
select profesional, nombre from public.turnos_medicos ptm inner join
	public.Usuarios pu on ptm.id_usuario = pu.id
