create table public.proveedores(
	id int primary key generated by default as identity (increment 1 start 1),
	nombre_proveedor text
);
create table public.usuarios(
	id int primary key generated by default as identity (increment 1 start 1),
	nombre_usuario text,
	apellido_usuaio text
);
create table public.vendedores(
	id int primary key generated by default as identity(increment 1 start 1),
	nombre_vendedor text,
	aprllido_vendedor text
);
create table public.productos(
	id int primary key generated by default as identity (increment 1 start 1 ),
	precion int,
	nombre text,
	id_proveedor int,
	constraint FK_proveedor foreign key (id_proveedor)
	references public.proveedores(id)
);

create table public.ventas(
	id int primary key generated by default as identity(increment 1 start 1),
	precio_venta bigint,
	id_producto int,
	id_vendedor int,
	id_usuario int,
	constraint FK_producto foreign key (id_producto)
	references public.productos(id),
	constraint FK_vendedor foreign key (id_vendedor)
	references public.vendedores(id),
	constraint FK_usuario foreign key (id_usuario)
	references  public.usuarios(id)
);

create table public.transportadores(
	id int primary key generated by default as identity (increment 1 start 1),
	nombre_transportador text,
	id_venta int,
	constraint FK_venta foreign key (id_venta)
	references public.ventas(id)
)

/* Agregar registros a la tabla proveedores*/
INSERT INTO public.proveedores (nombre_proveedor)
VALUES
    ('Proveedor A'),
    ('Proveedor B'),
    ('Proveedor C'),
    ('Proveedor D'),
    ('Proveedor E');

-- Agregar registros a la tabla usuarios
INSERT INTO public.usuarios (nombre_usuario, apellido_usuaio)
VALUES
    ('Juan', 'Perez'),
    ('Maria', 'Gomez'),
    ('Carlos', 'Rodriguez'),
    ('Laura', 'Lopez'),
    ('Andres', 'Martinez');

-- Agregar registros a la tabla vendedores
INSERT INTO public.vendedores (nombre_vendedor, aprllido_vendedor)
VALUES
    ('Vendedor 1', 'Apellido 1'),
    ('Vendedor 2', 'Apellido 2'),
    ('Vendedor 3', 'Apellido 3'),
    ('Vendedor 4', 'Apellido 4'),
    ('Vendedor 5', 'Apellido 5');

-- Agregar registros a la tabla productos
INSERT INTO public.productos (precion, nombre, id_proveedor)
VALUES
    (50, 'Producto X', 1),
    (75, 'Producto Y', 2),
    (120, 'Producto Z', 3),
    (90, 'Producto A', 4),
    (110, 'Producto B', 5);

-- Agregar registros a la tabla ventas
INSERT INTO public.ventas (precio_venta, id_producto, id_vendedor, id_usuario)
VALUES
    (250, 1, 1, 1),
    (225, 2, 2, 2),
    (240, 3, 3, 3),
    (280, 4, 4, 4),
    (200, 5, 5, 5);

-- Agregar registros a la tabla transportadores
INSERT INTO public.transportadores (nombre_transportador, id_venta)
VALUES
    ('Transportador A', 1),
    ('Transportador B', 2),
    ('Transportador C', 3),
    ('Transportador D', 4),
    ('Transportador E', 5);

